Move dracut files to usr lib dir
SUSE-Enceladus/microsoft-dracut-config pull request #2
Opened 2024-12-04 21:20 UTC by smarlowucf

2024-12-05 09:59 UTC, apozsuse approved these changes
LGTM

2025-01-06 16:32 UTC, jgleissner requested changes

2025-01-06 16:32 UTC, jgleissner commented on microsoft-dracut-config.spec
> +%{_libexecdir}dracut/dracut.conf.d/11-resume.conf
`%_libexecdir` expands to `/usr/libexec` in openSUSE and probably SLFO too. It's probably better to `/usr/lib` directly.

2025-01-06 18:04 UTC, smarlowucf commented
Rebased and merged the pr that drops the config macro.

2025-01-07 19:23 UTC, smarlowucf commented on microsoft-dracut-config.spec
> +%{_libexecdir}dracut/dracut.conf.d/11-resume.conf
Fixed. Using full path instead

2025-01-07 20:38 UTC, rjschwei approved these changes

2025-01-07 21:34 UTC, jgleissner approved these changes

2025-01-08 16:06 UTC, merged